### PR TITLE
Add Le Journal du Dimanche

### PR DESCRIPTION
**Pull request by iscreamcoke**
* Add [lejdd.fr](https://lejdd.fr) (blocking swisspay.ch, aka [smartwall.ai](http://www.smartwall.ai/), already in uBlock default list)

### CODE REVIEW

**Comment by magnolia1234** [comment]
If it's more widely used you can add SwissPay to general block-paywall list.
Also use full name for FdD in sites.json (next to other French papers).
Btw new line after ADR-papers was intended.

**Comment by iscreamcoke** [comment]
> If it's more widely used you can add SwissPay to general block-paywall list.

According to their website, it's used by other websites but blocking it had no effect.

> Also use full name for FdD in sites.json (next to other French papers).
Btw new line after ADR-papers was intended.

corrected

**Comment by magnolia1234** [comment]
A general paywall-block needs to be enabled via a sites.json entry.

**Comment by magnolia1234** [comment]
Ah, SwissPay isn't recognized as Javascript.
But blockedRegexes works fine.
Btw uBlock Origin doesn't show SwissPay as blocked (probably blocked at a higher level).

**Comment by iscreamcoke** [comment]
> Ah, SwissPay isn't recognized as Javascript.
But blockedRegexes works fine.
Btw uBlock Origin doesn't show SwissPay as blocked (probably blocked at a higher level).

Yes as long as it worked, I didn't ask myself why haha. Btw swisspay is the url used by le Journal du Dimanche, but it's a redirection towards http://www.smartwall.ai/

**Pull request merged**
