### PR TITLE
Add Libération + readme updates

### PR DESCRIPTION
**Pull request by iscreamcoke**
* reintroduce Libération 
* add forgotten 'BP Clean' in readme
* add support for Microsoft Edge in readme (tested on MacOS) – issue [#482](https://github.com/iamadamdev/bypass-paywalls-chrome/issues/482)

### CODE REVIEW

**Comment by magnolia1234** [comment]
Nice, but could you leave the DIY pre-'research' options?
Google search (checks Google referrer), incognito mode (block/refresh cookies) and block Javascript.
Users can include their findings in a request/issue (only a few sofar in my new repo though).

**Comment by iscreamcoke** [comment]
ok I'll add it back

**Comment by iscreamcoke** [comment]
done. are you ok with the wording?

**Comment by magnolia1234** [comment]
Yes, maybe a line about adding the results of their DIY research into the issue?
PS may I call you mr. marketing guy for BP Clean yet? ;-)

**Comment by iscreamcoke** [comment]
yes you can haha that's my job indeed

I've also removed the 'Only large or major sites will be considered' line since it contradicts the purpose of sites_custom.js

**Comment by magnolia1234** [comment]
I know, nice job.
Btw I think we can use the sites_custom-list purely for quick updates now.
I'm still considering reorganizing the supported sites in readme: major list + other sites subdivided over language and/or continent/country (more compact, comma-seperated).

**Comment by iscreamcoke** [comment]
> I'm still considering reorganizing the supported sites in readme: major list + other sites subdivided over language and/or continent/country (more compact, comma-seperated).

great idea, i'll do a pr

**Comment by magnolia1234** [comment]
PS interesting script: https://greasyfork.org/en/scripts/371681-la-stampa-topnews-full-text-articles

**Comment by iscreamcoke** [comment]
> PS interesting script: https://greasyfork.org/en/scripts/371681-la-stampa-topnews-full-text-articles
Nice, I'll look into it.

PS first draft: https://github.com/iscreamcoke/bypass-paywalls-chrome-clean/blob/master/README.md (further split may be added: Tech, Finance)

**Comment by iscreamcoke** [comment]
I'am also considering adding an asterisk * and a short note 'free articles only' below the section for relevant sites. What do you think?

**Comment by iscreamcoke** [comment]
also, I've not encountered this issue for months `Every time you open Chrome it may warn you about running extensions in developer mode, just click 🗙 to keep the extension enabled.`

I don't think it's relevant in newest Chrome versions

**Comment by iscreamcoke** [comment]
I also propose to change that line in the clean version: `Install the [Cookie Remover](https://chrome.google.com/webstore/detail/cookie-remover/kcgpggonjhmeaejebeoeomdlohicfhce) extension. Please rate it 5 stars if you find it useful.`

[This extension](https://chrome.google.com/webstore/detail/disable-cookies/lkmjmficaoifggpfapbffkggecbleang?hl=en) should be recommended instead

**Comment by magnolia1234** [comment]
Readme-update looks very nice (future-proof).
Tech and Finance would be usefull too.
Btw Towards Data Science is a Medium-site , but no harm to name it with Medium though.

**Comment by magnolia1234** [comment]
> also, I've not encountered this issue for months `Every time you open Chrome it may warn you about running extensions in developer mode, just click 🗙 to keep the extension enabled.`
> 
> I don't think it's relevant in newest Chrome versions

Still relevant on Windows though.

**Comment by iscreamcoke** [comment]
> Readme-update looks very nice (future-proof).
> Tech and Finance would be usefull too.
> Btw Towards Data Science is a Medium-site , but no harm to name it with Medium though.

I have added further divisions. The question is: should a British financial paper be referenced under 'Finance' or 'UK'. I've favoured the latter for the moment.

**Comment by magnolia1234** [comment]
Or name them in both.
I think you can start the seperate European countries on a new line.

**Comment by magnolia1234** [comment]
PS some weblinks are not working (no https-prefix).

**Comment by iscreamcoke** [comment]
> PS some weblinks are not working (no https-prefix).

fixed.

> I think you can start the seperate European countries on a new line.

I did that at first, but it make the whole list longer. What do you think of the organisation for 'United Stated' for instance?

**Comment by magnolia1234** [comment]
Some a bit abitrary subdivision.
The Atlantic is more about politics.
Btw Bloomberg Quint is for India market.

**Comment by iscreamcoke** [comment]
> Btw Bloomberg Quint is for India market.

corrected

> Some a bit arbitrary subdivision.

what do you propose instead? removing subdivsions

**Comment by iscreamcoke** [comment]
btw could you apply the github label 'enhancements' for new site requests? I'll link the 'check previous requests' to it in the readme.

**Comment by magnolia1234** [comment]
Principle of divisions is good, but you'll always have a list of 'odd' sites (maybe custom?).
Btw SofRep is about military. Challenges.fr/Valeurs Actuelles were never added on their own though.

**Comment by iscreamcoke** [comment]
> Challenges.fr/Valeurs Actuelles were never added on their own though.

yes, but they're bypassed by general scripts, like O Globo (which I also added) and others like Digiday (I realised it yesterday night)

this is just a proposition. Should we add any website known to work in the supported list?

**Comment by magnolia1234** [comment]
I'll update a revision of your new readme in a few minutes.
Only sites in the options for the moment.

**Comment by magnolia1234** [comment]
Just comitted a readme-update with site per line (for maintenance).

**Comment by iscreamcoke** [comment]
yes good commit.

I would have just replaced 'Newspapers/Magazines' with 'general' since all sites are newspapers or magazines.
Encyclopedia Britannica is British but I don't think it's relevant to put them in 'US' since none of the websites listed in this category are region-specific
Bonus: as per styling standard,  all sites should be in italic as the name of a newspaper/magazine

**Comment by iscreamcoke** [comment]
btw I had corrected a typo in the new website request instructions. Now read:

> You can submit a request for a new website [here](https://github.com/magnolia1234/bypass-paywalls-chrome-clean/issues/new). Please read the following instructions and share your results for a quicker process. Remember to check the [previous requests](https://github.com/magnolia1234/bypass-paywalls-chrome-clean/issues?q=is%3Aissue+label%3Aenhancement) before asking for a new website.

**Comment by magnolia1234** [comment]
I copied your version first or more changes?
Headers are a work in progress, I guess.

**Comment by iscreamcoke** [comment]
the current version on your repo is good.

Yes headers are still a subject of discussion, but the list is better than before. Just limited cosmetic improvement remaining

**Comment by iscreamcoke** [comment]
Other possible layout with headers-only: https://github.com/iscreamcoke/bypass-paywalls-chrome-clean/blob/master/README.md

**Comment by magnolia1234** [comment]
Looks fine to me, but ... ;-)
* general header is a bit too general
* could you give Medium a more prominent place (btw BP works for all Medium sites, like Towards Data Science)? Maybe fits in the Blogs category?
* replacing Cookie Remover as you suggested is fine with me?

**Comment by iscreamcoke** [comment]
> replacing Cookie Remover as you suggested is fine with me.
> could you give Medium a more prominent place (btw BP works for all Medium sites, like Towards Data Science)? Maybe fits in the Blogs category?

done

> general header is a bit too general

Maybe 'Politics & Culture' would fit those websites.

**Comment by iscreamcoke** [comment]
I was also thinking of directing the 'github' hyperlink in 'options.html' towards the readme rather than repo base. To make it more user-friendly.

What do you think of it?

**Comment by magnolia1234** [comment]
> Maybe 'Politics & Society' would fit those websites?

Sounds familiar ;-)
I was looking for some more contrast with 'Local news' like World news(magazines).

**Comment by iscreamcoke** [comment]
> I was looking for some more contrast with 'Local news' like World news(magazines).

done, replaced with 'world news'

**Comment by magnolia1234** [comment]
Nice.
Could you all sies to Medium?
If you like you can also add a PR with the French and Brazilian sites (with blocked paywall-scripts), but then also in sites.json and blockedRegexes.
About time for a new release ;-)

**Pull request merged**
