### PR TITLE
Add Australian newspapers + Fix lesechos.fr & thetimes.co.uk

### PR DESCRIPTION
**Pull request by iscreamcoke**
* Add The Advertiser, The Courier-Mail, Northern Territory News, The Daily Telegraph, Herald Sun, Gold Coast Bulletin, Townsville Bulletin, Cairns Post, The Weekly Times.
* Fix The Mercury.
* Fix Les Échos & The Times (block ad blocks not fully removed by uBlock default lists (black spaces inside the articles when the ad was supposed to appear) | with uBlock deactivated, it'll also remove the ads.)

### CODE REVIEW

**Comment by iscreamcoke** [comment]
Please also consider adding a picture to your profile. It'll the repo more 'serious' ;-) @magnolia1234

**Comment by iscreamcoke** [comment]
I have changed the hyperlink of option.html to point to the readme instead. It's a proposition open to discussion to make it more user-friendly.

**Comment by iscreamcoke** [comment]
I have made several variations of a logo inspired by that of the NYT:

Screen Shot 2020-01-26 at 10 54 06
Screen Shot 2020-01-26 at 10 54 17
Screen Shot 2020-01-26 at 10 54 49
Screen Shot 2020-01-26 at 10 55 49
Screen Shot 2020-01-26 at 10 56 09

**Comment by iscreamcoke** [comment]
I have closed the PR for moment. I'm running tests for the landing page and it needs to be done on the master branch. Stay tuned

**Comment by magnolia1234** [comment]
Nice logo, also for dark theme.

**Comment by magnolia1234** [comment]
> Please also consider adding a picture to your profile. It'll make the repo appear more 'serious' ;-) @magnolia1234

Says the guy who's nickname is 'iscreamcoke'? ;-)
Btw wouldn't you hide your Gmail (visible in PR patch-links)?

**Comment by magnolia1234** [comment]
PS very similar to WaPo-logo.

**Comment by iscreamcoke** [comment]
ah haven't realized it. I took inspiration from the NYT [minimal logo](https://slysslidersandfries.com/wp-content/uploads/2017/08/nyt-t-logo.png). Many newspapers use this kind of font (LA Times, Times of London, Le Monde, etc.)

**Comment by iscreamcoke** [comment]
PS Adam finally blocked me

**Comment by magnolia1234** [comment]
Never mind, he's still just copying our fixes.
PS I was already blocked early this morning ;-)

**Comment by iscreamcoke** [comment]
Well, let's continue as usual, we'll beat him in the long run with our reactivity and exclusivities (e.g., The Athletic.) 

I'm going to build a clean and SEO-friendly landing page to take most of Google searches. (Too bad it's contrary to Google/Facebook policies, I would have also put ads everywhere)

**Comment by magnolia1234** [comment]
Relax, also with the ads-talk will you? ;-)
You're not 'watching' my repo for e-mail notifications? 

Btw have you seen jimmydeuxfois' unblocking himself after renaming his account (iamadamde)?
Not a solution for us as contributors, but still nice (Adam's issue 485):
_llacb47 you're out of the loop kid. Adam has just been clicking 'merge PR' and copying fixes from other repos for the last 5 months. You won't see any update this year as he banned all the big contributors.
just look at this: https://github.com/iamadamdev/bypass-paywalls-chrome/commits/master_

**Comment by iscreamcoke** [comment]
> Relax, also with the ads-talk will you? ;-)

It was a joke (except the landing page). I must admit however that there's one thing Adam is right about, we should have added 'thanks to  iamadamdev at the end of the readme'.

> You're not 'watching' my repo for e-mail notifications?

I just receive email when you answer. When I get a notification and I have to time to answer, I do it right now not to forget later.

> Btw have you seen jimmydeuxfois' unblocking himself after renaming his account (iamadamde)?

What? Why was he blocked in the first way, because he had published an issue on your repo?

**Comment by iscreamcoke** [comment]
> Relax, also with the ads-talk will you? ;-)

It was a joke (except the landing page). I must admit however that there's one thing Adam is right about, we should just have added 'thanks to  iamadamdev' at the end of the readme (he didn't do it for us, but that's not a reason to act like him).

> You're not 'watching' my repo for e-mail notifications?

I just receive an email when you answer. When I get a notification and I have to time to answer, I do it right now not to forget later.

> Btw have you seen jimmydeuxfois' unblocking himself after renaming his account (iamadamde)?

What? Why was he blocked in the first place, because he had published an issue on your repo?  I'm sure Adam will appreciate the new name/impersonation of him.

**Comment by magnolia1234** [comment]
> I just receive an email when you answer. When I get a notification and I have to time to answer, I do it right now not to forget later.

No worries, I just didn't see you in the list of people watching my repo.

> What? Why was he blocked in the first place, because he had published an issue on your repo? I'm sure not really Adam will appreciate the new name/impersonation of him...

For telling the truth about Adam's repo and our alternative.
But lousy way of blocking by GitHub then (jimmy's old comments are still visible).

**Comment by iscreamcoke** [comment]
> No worries, I just didn't see you in the list of people watching my repo.

Well, it's done now.

ps: what do you think of the comment I have added to your message in issues?

**Comment by magnolia1234** [comment]
Fit to print :-)

**Comment by iscreamcoke** [comment]
No way to pin a comment in 'issues' as the repo owner?

btw: I've send your repo to a lot of people (instead of Adam's one, but at first it about the updates, not the 'conflict').

If everything goes right, everyone'll be using it in Paris in several months (I even heard of people mentioning the repo while I hadn't talked to them about it before. It just friends of friends for the moment, but i'll expand ;) )

**Comment by iscreamcoke** [comment]
No way to pin a post in 'issues' as the repo owner?

btw: I've send your repo to a lot of people (instead of Adam's one, but at first it was about the updates, not the 'conflict').

If everything goes right, everyone will be using it in Paris within several months ;) (I even heard of people mentioning the repo while I hadn't talked to them about it before. It's just friends of friends of friends for the moment, but i'll expand ;) )

**Comment by iscreamcoke** [comment]
To main reasons for the 'success': the support of French newspapers (hence the importance to think 'worldwide') and of Haaretz (Paris has first Jewish community in Europe).

I'll stop now, I'm beginning to talk like a marketer ;-)

**Comment by magnolia1234** [comment]
Occupational hazard ;-)

**Comment by iscreamcoke** [comment]
Do you think I've crossed the border by proposing a free-pdf sites for newspapers in: https://github.com/magnolia1234/bypass-paywalls-chrome-clean/issues/21

I don't know GitHub policy (and especially the use of bots to track url). I don't want the repo to be banned just for one (very helpful) comment.

**Comment by iscreamcoke** [comment]
wtf, is this dude a magician? He's back with his old pseudo and advertising your repo in every comment 

Screen Shot 2020-01-28 at 20 37 23

**Comment by magnolia1234** [comment]
> wtf, is this dude a magician? He's back with his old pseudo and advertising your repo in every comment

He's really pissed off, I guess ;-)

**Comment by iscreamcoke** [comment]
Well he has been asking for several new requests. If the only answer he got is "see https://github.com/iamadamdev/bypass-paywalls-chrome#new-site-requests" (instead of "we've looked into it, unfortunately it's a hard paywall"), I can understand why he's pissed off.

-------

btw could you explain what this code does concretely?
```
chrome.webRequest.handlerBehaviorChanged(function () {});
					break;	
```

**Comment by magnolia1234** [comment]
Crude way to reload eventlistener when you want to selectively load or not load a paywall-script.
Otherwise the script gets cached when you want to block it.

**Pull request closed without merging**
