### PR TITLE
Add Australian newspapers

### PR DESCRIPTION
**Pull request by iscreamcoke**
* Add The Advertiser, The Courier-Mail, Northern Territory News, The Daily Telegraph, Herald Sun, Gold Coast Bulletin, Townsville Bulletin, Cairns Post, The Weekly Times.
* Fix Examiner.com.au, The Mercury.
* Fix Les Échos & The Times (ad blocks not fully removed by uBlock default lists (black spaces inside the articles when the ad was supposed to appear) | with uBlock deactivated, it'll also remove the ads.)

### CODE REVIEW

**Comment by magnolia1234** [comment]
PS which Mercury fix?

**Comment by iscreamcoke** [comment]
> Do all the Australian sites actually need Googlebot set (also tested?)?

Yes they do (News Corp corporation, the few ones that didn't work were filtered out)

> Btw I'm not going to merge a subfolder for js-files though (cosmetic change).

ok... corrected

> PS which Mercury fix?

themercury.com.au needs googlebot to read premium articles

**Comment by magnolia1234** [comment]
> Yes they do (News Corp media group, the few ones that didn't work were filtered out)

I recognized an old request from Adam's repo.

**Comment by magnolia1234** [comment]
> themercury.com.au needs googlebot to read premium articles

Okay, I was just synching site from Firefox add-on.

**Comment by iscreamcoke** [comment]
> I recognized an old request from Adam's repo.

Yes indeed, I began with adding The Herald after a request on Adam's repo, then I remembered that PR that was never introduced.

I have tested all of them though, and the list is not the same as the old PR's one.

**Comment by magnolia1234** [comment]
> themercury.com.au needs googlebot to read premium articles

PS do you have a example of a premium articles which need Googlebot (subscriber-only articles are working just fine for me)?

**Comment by iscreamcoke** [comment]
> PS do you have a example of a premium articles which need Googlebot (subscriber-only articles are working just fine for me)?

I'm having a cookie issue without the google-bot on my side (similar issue on the NYT back in early December)

sample: https://www.themercury.com.au/business/tasmanians-dont-visit-hobarts-cbd-like-they-once-did-industry-leaders-say/news-story/87ca6ccb6d90f2b83259f85db79e50c7

**Comment by magnolia1234** [comment]
Weird, article is working just fine for me.
But cookie-issue like NYT?

**Comment by iscreamcoke** [comment]
> But cookie-issue like NYT?

It was in October. Same cookie issue without googbot.

Remember: https://github.com/iamadamdev/bypass-paywalls-chrome/issues/340

https://github.com/magnolia1234/bypass-paywalls-chrome-clean/commit/e5ec01abd996541347f3f7d39bf14bd5e6cd2f06

**Comment by magnolia1234** [comment]
Btw no reversioning in PR's please.

**Comment by iscreamcoke** [comment]
> Btw no reversioning in PR's please.

reverted

**Comment by magnolia1234** [comment]
I can't delete your .DS_Store though.

**Comment by iscreamcoke** [comment]
> I can't delete your .DS_Store though.

done (temporary mac file)

**Comment by magnolia1234** [comment]
Thanks, just squashed and merged.

**Comment by magnolia1234** [comment]
You unforked by accident or did you go back to the 'dark' side? ;-)

**Comment by iscreamcoke** [comment]
> You unforked by accident or did you go back to the 'dark' side? ;-)

I unforked because my edits were over (and because I never managed to synchronize the repos after a PR, so I delete and refork)

**Comment by magnolia1234** [comment]
Ah, familiar issue with Adam's repo before (he's still 'begging').

Reset to master-origin

git fetch upstream
git reset --hard upstream/master
git push -f

**Pull request merged**
