### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by thesummit**
should be a noop. there's a bunch of preexisting broken code which i didn't try to fix.

### CODE REVIEW

**Comment by magnolia1234** [comment]
Well El Jefe, you ran some JsLint/JsFiddle transpiler on my files (changes only to styling, renaming and functions in arrow (ES6) notation) and ended up with a non-operating extension.
No use of complaining about pre-existing 'broken' code though (it's working just fine) ...

**Comment by thesummit** [comment]
That's really creepy. Where did you get that from?

**Comment by magnolia1234** [comment]
>That's really creepy. Where did you get that from?

PR patch-file shows your full name and mailaddress.
By default these are hidden though.

**Comment by danielgruber8** [comment]
how come it got closed?

**Comment by magnolia1234** [comment]
Summit closed it and also deleted his fork and account, but I still have his old fork of Adam's repo (more interesting). This PR didn't contain any new functionality though.

**Pull request closed without merging**
