### PR TITLE
Add O Globo, O Estado de S. Paulo, Exame, Challenges.fr, Valeurs Actuelles, Digiday + readme updates

### PR DESCRIPTION
**Pull request by iscreamcoke**

### CODE REVIEW

**Comment by magnolia1234** [comment]
Old comment (more sites):

> * Folha de São Paulo ( https://www.folha.uol.com.br/ )

Use uBlock Origin with (default) filter Easylist -> /publicidade.

> Valor Econômico ( https://valor.globo.com/ )
> O Globo ( https://oglobo.globo.com/ )
> Exame ( https://exame.abril.com.br/ )

Use uBlock Origin and enable filter Fanboy’s Enhanced Tracking List -> ||tinypass.com^$3p

**Comment by iscreamcoke** [comment]
Valor Econômico doesn't work with tinypass blocked though

**Comment by magnolia1234** [comment]
Just add one domain voor globo.com plus line in blockedRegexes.
O Globo works for all articles, but Valor Econômico only for free articles.

**Comment by magnolia1234** [comment]
Almost, just one line in sites.json (only globo.com cookies for both sites): "Globo": "globo.com",

**Comment by magnolia1234** [comment]
Just **one** line "Globo": "globo.com",
No O Globo or Valor in sites.json (in readme is no problem though).

**Comment by iscreamcoke** [comment]
done; btw I'm trying to add O Estado de S. Paulo by can't remove dom element

**Comment by magnolia1234** [comment]
Does Estadao even have a paywall?

**Comment by iscreamcoke** [comment]
yes, certain articles are subcribers-only but the paywall is easy to work around:

`data-modal="conteudo_exclusivo"` or `###paywall-iframe-estadao`

https://economia.estadao.com.br/noticias/geral,quem-compra-o-brasil,70003163757

**Comment by magnolia1234** [comment]
Ah, but you're trying to remove the element with class paywall-iframe-estadao.
It's element with id so css-selector #paywall-iframe-estado or getElementById

**Comment by iscreamcoke** [comment]
thanks it worked

**Comment by magnolia1234** [comment]
Or remove parent-div #paywall-wrapper-iframe-estadao

**Comment by iscreamcoke** [comment]
done

**Comment by magnolia1234** [comment]
Really, no more commits? ;-)

**Comment by magnolia1234** [comment]
PS I'll make a new release tomorrow morning to give you some more time :-)

**Comment by magnolia1234** [comment]
Btw it might be usefull to divide the Latin American sites up by country when you're going to add them 'all' ;-)

**Comment by iscreamcoke** [comment]
> PS I'll make a new release tomorrow morning to give you some more time :-)

I'm going to rest now ;-) i'll catch the new release tomorrow

**Comment by iscreamcoke** [comment]
Just two quick re-ordering in the readme : (1) in local news: "Los Angeles Business Journal" should be before "Miami Herald" (2) in UK: "The Times Literary Supplement" should be after "The Times".

> Btw it might be usefull to divide the Latin American sites up by country when you're going to add them 'all' ;-)
Yes, we're beginning to have enough Latin American papers to split the sections. I'll do it the next times we add sites to this category.

Nice release, nice work!

**Comment by magnolia1234** [comment]
No worries, I'll pick it up in a next commit.

**Comment by iscreamcoke** [comment]
btw would you be interested in a new icon (even just slightly different from the current one) in order to distinguish the clean version from the old one?

btw2 [GitHub Pages](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site) is a good and quick solution to create a landing page from a GitHub repo.

**Comment by iscreamcoke** [comment]
btw3 the icon is duplicated in the extension: there's bypass.png and icon.png

**Comment by magnolia1234** [comment]
A new icon is a good idea.
Icon.png is still used in popup.html, but someone forgot to edit it while renaming the icon ;-)

**Comment by iscreamcoke** [comment]
I did some further alphabetical re-reordering and divided América Latina (the same could be done for India/South Asia and Israel/Middle East in case we have websites from other countries in those regions)

https://github.com/iscreamcoke/bypass-paywalls-chrome-clean/blob/master/README.md

ps: the icon was renamed to icon.png rather than bypass.png if I remember correctly

**Comment by magnolia1234** [comment]
That was not the issue (just the editing) :-)

**Comment by iscreamcoke** [comment]
I know I meant it should be icon.png everywhere.

btw I have also updated the installation instructions for Edge (works for both Windows and MacOS (tested) while the previous instruction were apparently Mac-only)

https://github.com/iscreamcoke/bypass-paywalls-chrome-clean/blob/master/README.md

**Comment by iscreamcoke** [comment]
also corrected a typo in my readme (along side > alongside)

**Comment by magnolia1234** [comment]
Crx-file works for me on Chromium-Edge too though.

**Comment by iscreamcoke** [comment]
> Crx-file works for me on Chromium-Edge too though.

As you wish, pick what you think is good in my version of the readme

**Pull request merged**
