### PR TITLE
Fix dn.se/chicagobusiness.com + readme updates

### PR DESCRIPTION
**Pull request by iscreamcoke**

### CODE REVIEW

**Comment by iscreamcoke** [comment]
btw I've generated a github page from the readme. This is simple to do, though I see no real use except cleaner url and better SEO

https://iscreamcoke.github.io/bypass-paywalls-chrome-clean/

**Comment by iscreamcoke** [comment]
btw what do we with those ad_blocks? backgroun.js or uBlock list?

```
! 2 | ad_blocks not fully removed by uBlock default lists
!
www.lesechos.fr##.fESsUe
www.lesechos.fr##.fAcjgi
www.lesechos.fr##.qxebl
www.wsj.com###wrapper-AD_PUSH
www.thetimes.co.uk###ad-article-inline
```

**Comment by magnolia1234** [comment]
Convert them to ContentScript.js for now, I guess.
Btw Adam is 'alive' and bitching about me while also using my old PR fixes (old story) ;-)

**Comment by iscreamcoke** [comment]
He's going to ban me I think, for which I don't care: nobody is going to submit commits (not even him) on his repo if we're both banned

**Comment by magnolia1234** [comment]
Relax, but you caved in at the end ;-)
I'm not going to commit to Adam's repo again.
He'll just remove your comments though.

**Comment by iscreamcoke** [comment]
> Relax, but you caved in at the end ;-)

I removed the 'conciliatory part' (second comment) since it's not going to happen and I'm about to be banned anyway for having said what I think in the first place.

**Pull request merged**
